// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: ozon/v1/ozon.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code  string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Role) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenValidation bool    `protobuf:"varint,1,opt,name=tokenValidation,proto3" json:"tokenValidation,omitempty"`
	UserID          int64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	CompanyID       int64   `protobuf:"varint,3,opt,name=companyID,proto3" json:"companyID,omitempty"`
	Roles           []*Role `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetTokenValidation() bool {
	if x != nil {
		return x.TokenValidation
	}
	return false
}

func (x *AuthRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AuthRequest) GetCompanyID() int64 {
	if x != nil {
		return x.CompanyID
	}
	return 0
}

func (x *AuthRequest) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type BoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BoolReply) Reset() {
	*x = BoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolReply) ProtoMessage() {}

func (x *BoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolReply.ProtoReflect.Descriptor instead.
func (*BoolReply) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{2}
}

func (x *BoolReply) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type OzonAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID int32  `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ApiKey   string `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Error    bool   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *OzonAuth) Reset() {
	*x = OzonAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OzonAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OzonAuth) ProtoMessage() {}

func (x *OzonAuth) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OzonAuth.ProtoReflect.Descriptor instead.
func (*OzonAuth) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{3}
}

func (x *OzonAuth) GetClientID() int32 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *OzonAuth) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *OzonAuth) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type SetOzonAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth     *AuthRequest `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	OzonAuth *OzonAuth    `protobuf:"bytes,2,opt,name=ozonAuth,proto3" json:"ozonAuth,omitempty"`
}

func (x *SetOzonAuthRequest) Reset() {
	*x = SetOzonAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOzonAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOzonAuthRequest) ProtoMessage() {}

func (x *SetOzonAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOzonAuthRequest.ProtoReflect.Descriptor instead.
func (*SetOzonAuthRequest) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{4}
}

func (x *SetOzonAuthRequest) GetAuth() *AuthRequest {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *SetOzonAuthRequest) GetOzonAuth() *OzonAuth {
	if x != nil {
		return x.OzonAuth
	}
	return nil
}

type ProductCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ProductCount) Reset() {
	*x = ProductCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCount) ProtoMessage() {}

func (x *ProductCount) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCount.ProtoReflect.Descriptor instead.
func (*ProductCount) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{5}
}

func (x *ProductCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DaySales struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayName string `protobuf:"bytes,1,opt,name=dayName,proto3" json:"dayName,omitempty"`
	Date    string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Count   int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sum     int64  `protobuf:"varint,4,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *DaySales) Reset() {
	*x = DaySales{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaySales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySales) ProtoMessage() {}

func (x *DaySales) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySales.ProtoReflect.Descriptor instead.
func (*DaySales) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{6}
}

func (x *DaySales) GetDayName() string {
	if x != nil {
		return x.DayName
	}
	return ""
}

func (x *DaySales) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DaySales) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DaySales) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type WidgetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductCount *ProductCount `protobuf:"bytes,1,opt,name=productCount,proto3" json:"productCount,omitempty"`
	DaySales     []*DaySales   `protobuf:"bytes,2,rep,name=daySales,proto3" json:"daySales,omitempty"`
}

func (x *WidgetReply) Reset() {
	*x = WidgetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozon_v1_ozon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetReply) ProtoMessage() {}

func (x *WidgetReply) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_v1_ozon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetReply.ProtoReflect.Descriptor instead.
func (*WidgetReply) Descriptor() ([]byte, []int) {
	return file_ozon_v1_ozon_proto_rawDescGZIP(), []int{7}
}

func (x *WidgetReply) GetProductCount() *ProductCount {
	if x != nil {
		return x.ProductCount
	}
	return nil
}

func (x *WidgetReply) GetDaySales() []*DaySales {
	if x != nil {
		return x.DaySales
	}
	return nil
}

var File_ozon_v1_ozon_proto protoreflect.FileDescriptor

var file_ozon_v1_ozon_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x7a, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6f, 0x7a, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x8f, 0x01, 0x0a,
	0x0b, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x05,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6f, 0x7a,
	0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x23,
	0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x54, 0x0a, 0x08, 0x4f, 0x7a, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x67, 0x0a, 0x12, 0x53, 0x65, 0x74,
	0x4f, 0x7a, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x2a, 0x0a, 0x08, 0x6f, 0x7a, 0x6f, 0x6e, 0x41, 0x75,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e,
	0x4f, 0x7a, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x08, 0x6f, 0x7a, 0x6f, 0x6e, 0x41, 0x75,
	0x74, 0x68, 0x22, 0x24, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x08, 0x44, 0x61, 0x79, 0x53,
	0x61, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x22, 0x71, 0x0a, 0x0b, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x79, 0x53, 0x61,
	0x6c, 0x65, 0x73, 0x52, 0x08, 0x64, 0x61, 0x79, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x32, 0xe6, 0x01,
	0x0a, 0x04, 0x4f, 0x7a, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4f, 0x7a, 0x6f,
	0x6e, 0x41, 0x75, 0x74, 0x68, 0x12, 0x18, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74,
	0x4f, 0x7a, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4f, 0x7a, 0x6f, 0x6e, 0x41, 0x75, 0x74,
	0x68, 0x12, 0x11, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x4f, 0x7a, 0x6f, 0x6e,
	0x41, 0x75, 0x74, 0x68, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4f,
	0x7a, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x12, 0x11, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6f, 0x7a, 0x6f,
	0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11,
	0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x73, 0x61, 0x6e, 0x79, 0x63, 0x68, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ozon_v1_ozon_proto_rawDescOnce sync.Once
	file_ozon_v1_ozon_proto_rawDescData = file_ozon_v1_ozon_proto_rawDesc
)

func file_ozon_v1_ozon_proto_rawDescGZIP() []byte {
	file_ozon_v1_ozon_proto_rawDescOnce.Do(func() {
		file_ozon_v1_ozon_proto_rawDescData = protoimpl.X.CompressGZIP(file_ozon_v1_ozon_proto_rawDescData)
	})
	return file_ozon_v1_ozon_proto_rawDescData
}

var file_ozon_v1_ozon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ozon_v1_ozon_proto_goTypes = []interface{}{
	(*Role)(nil),               // 0: ozon.Role
	(*AuthRequest)(nil),        // 1: ozon.AuthRequest
	(*BoolReply)(nil),          // 2: ozon.BoolReply
	(*OzonAuth)(nil),           // 3: ozon.OzonAuth
	(*SetOzonAuthRequest)(nil), // 4: ozon.SetOzonAuthRequest
	(*ProductCount)(nil),       // 5: ozon.ProductCount
	(*DaySales)(nil),           // 6: ozon.DaySales
	(*WidgetReply)(nil),        // 7: ozon.WidgetReply
}
var file_ozon_v1_ozon_proto_depIdxs = []int32{
	0, // 0: ozon.AuthRequest.roles:type_name -> ozon.Role
	1, // 1: ozon.SetOzonAuthRequest.auth:type_name -> ozon.AuthRequest
	3, // 2: ozon.SetOzonAuthRequest.ozonAuth:type_name -> ozon.OzonAuth
	5, // 3: ozon.WidgetReply.productCount:type_name -> ozon.ProductCount
	6, // 4: ozon.WidgetReply.daySales:type_name -> ozon.DaySales
	4, // 5: ozon.Ozon.SetOzonAuth:input_type -> ozon.SetOzonAuthRequest
	1, // 6: ozon.Ozon.GetOzonAuth:input_type -> ozon.AuthRequest
	1, // 7: ozon.Ozon.ErrorOzonAuth:input_type -> ozon.AuthRequest
	1, // 8: ozon.Ozon.GetWidgetData:input_type -> ozon.AuthRequest
	2, // 9: ozon.Ozon.SetOzonAuth:output_type -> ozon.BoolReply
	3, // 10: ozon.Ozon.GetOzonAuth:output_type -> ozon.OzonAuth
	2, // 11: ozon.Ozon.ErrorOzonAuth:output_type -> ozon.BoolReply
	7, // 12: ozon.Ozon.GetWidgetData:output_type -> ozon.WidgetReply
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ozon_v1_ozon_proto_init() }
func file_ozon_v1_ozon_proto_init() {
	if File_ozon_v1_ozon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ozon_v1_ozon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OzonAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOzonAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaySales); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozon_v1_ozon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ozon_v1_ozon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ozon_v1_ozon_proto_goTypes,
		DependencyIndexes: file_ozon_v1_ozon_proto_depIdxs,
		MessageInfos:      file_ozon_v1_ozon_proto_msgTypes,
	}.Build()
	File_ozon_v1_ozon_proto = out.File
	file_ozon_v1_ozon_proto_rawDesc = nil
	file_ozon_v1_ozon_proto_goTypes = nil
	file_ozon_v1_ozon_proto_depIdxs = nil
}
