// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: ozon.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OzonClient is the client API for Ozon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OzonClient interface {
	SetOzonAuth(ctx context.Context, in *SetOzonAuthRequest, opts ...grpc.CallOption) (*BoolReply, error)
	GetOzonAuth(ctx context.Context, in *Access, opts ...grpc.CallOption) (*OzonAuth, error)
	ErrorOzonAuth(ctx context.Context, in *Access, opts ...grpc.CallOption) (*BoolReply, error)
	GetWidgetData(ctx context.Context, in *Access, opts ...grpc.CallOption) (*WidgetReply, error)
	GetProductList(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*ShopProductList, error)
	GetProduct(ctx context.Context, in *ShopProductRequest, opts ...grpc.CallOption) (*ShopProduct, error)
	SearchShopProduct(ctx context.Context, in *SearchShopProductRequest, opts ...grpc.CallOption) (*ShopProductList, error)
	GetUnsortedCount(ctx context.Context, in *Access, opts ...grpc.CallOption) (*ProductCount, error)
	GetUnsortedList(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*ShopProductList, error)
}

type ozonClient struct {
	cc grpc.ClientConnInterface
}

func NewOzonClient(cc grpc.ClientConnInterface) OzonClient {
	return &ozonClient{cc}
}

func (c *ozonClient) SetOzonAuth(ctx context.Context, in *SetOzonAuthRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/SetOzonAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) GetOzonAuth(ctx context.Context, in *Access, opts ...grpc.CallOption) (*OzonAuth, error) {
	out := new(OzonAuth)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/GetOzonAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) ErrorOzonAuth(ctx context.Context, in *Access, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/ErrorOzonAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) GetWidgetData(ctx context.Context, in *Access, opts ...grpc.CallOption) (*WidgetReply, error) {
	out := new(WidgetReply)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/GetWidgetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) GetProductList(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*ShopProductList, error) {
	out := new(ShopProductList)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/GetProductList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) GetProduct(ctx context.Context, in *ShopProductRequest, opts ...grpc.CallOption) (*ShopProduct, error) {
	out := new(ShopProduct)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) SearchShopProduct(ctx context.Context, in *SearchShopProductRequest, opts ...grpc.CallOption) (*ShopProductList, error) {
	out := new(ShopProductList)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/SearchShopProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) GetUnsortedCount(ctx context.Context, in *Access, opts ...grpc.CallOption) (*ProductCount, error) {
	out := new(ProductCount)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/GetUnsortedCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ozonClient) GetUnsortedList(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*ShopProductList, error) {
	out := new(ShopProductList)
	err := c.cc.Invoke(ctx, "/protocol.Ozon/GetUnsortedList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OzonServer is the server API for Ozon service.
// All implementations must embed UnimplementedOzonServer
// for forward compatibility
type OzonServer interface {
	SetOzonAuth(context.Context, *SetOzonAuthRequest) (*BoolReply, error)
	GetOzonAuth(context.Context, *Access) (*OzonAuth, error)
	ErrorOzonAuth(context.Context, *Access) (*BoolReply, error)
	GetWidgetData(context.Context, *Access) (*WidgetReply, error)
	GetProductList(context.Context, *SelectRequest) (*ShopProductList, error)
	GetProduct(context.Context, *ShopProductRequest) (*ShopProduct, error)
	SearchShopProduct(context.Context, *SearchShopProductRequest) (*ShopProductList, error)
	GetUnsortedCount(context.Context, *Access) (*ProductCount, error)
	GetUnsortedList(context.Context, *SelectRequest) (*ShopProductList, error)
	mustEmbedUnimplementedOzonServer()
}

// UnimplementedOzonServer must be embedded to have forward compatible implementations.
type UnimplementedOzonServer struct {
}

func (UnimplementedOzonServer) SetOzonAuth(context.Context, *SetOzonAuthRequest) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetOzonAuth not implemented")
}
func (UnimplementedOzonServer) GetOzonAuth(context.Context, *Access) (*OzonAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOzonAuth not implemented")
}
func (UnimplementedOzonServer) ErrorOzonAuth(context.Context, *Access) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrorOzonAuth not implemented")
}
func (UnimplementedOzonServer) GetWidgetData(context.Context, *Access) (*WidgetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWidgetData not implemented")
}
func (UnimplementedOzonServer) GetProductList(context.Context, *SelectRequest) (*ShopProductList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductList not implemented")
}
func (UnimplementedOzonServer) GetProduct(context.Context, *ShopProductRequest) (*ShopProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedOzonServer) SearchShopProduct(context.Context, *SearchShopProductRequest) (*ShopProductList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchShopProduct not implemented")
}
func (UnimplementedOzonServer) GetUnsortedCount(context.Context, *Access) (*ProductCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnsortedCount not implemented")
}
func (UnimplementedOzonServer) GetUnsortedList(context.Context, *SelectRequest) (*ShopProductList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnsortedList not implemented")
}
func (UnimplementedOzonServer) mustEmbedUnimplementedOzonServer() {}

// UnsafeOzonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OzonServer will
// result in compilation errors.
type UnsafeOzonServer interface {
	mustEmbedUnimplementedOzonServer()
}

func RegisterOzonServer(s grpc.ServiceRegistrar, srv OzonServer) {
	s.RegisterService(&Ozon_ServiceDesc, srv)
}

func _Ozon_SetOzonAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOzonAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).SetOzonAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/SetOzonAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).SetOzonAuth(ctx, req.(*SetOzonAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_GetOzonAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Access)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).GetOzonAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/GetOzonAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).GetOzonAuth(ctx, req.(*Access))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_ErrorOzonAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Access)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).ErrorOzonAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/ErrorOzonAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).ErrorOzonAuth(ctx, req.(*Access))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_GetWidgetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Access)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).GetWidgetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/GetWidgetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).GetWidgetData(ctx, req.(*Access))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_GetProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).GetProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/GetProductList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).GetProductList(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).GetProduct(ctx, req.(*ShopProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_SearchShopProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShopProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).SearchShopProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/SearchShopProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).SearchShopProduct(ctx, req.(*SearchShopProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_GetUnsortedCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Access)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).GetUnsortedCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/GetUnsortedCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).GetUnsortedCount(ctx, req.(*Access))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ozon_GetUnsortedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServer).GetUnsortedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Ozon/GetUnsortedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServer).GetUnsortedList(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ozon_ServiceDesc is the grpc.ServiceDesc for Ozon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ozon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Ozon",
	HandlerType: (*OzonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetOzonAuth",
			Handler:    _Ozon_SetOzonAuth_Handler,
		},
		{
			MethodName: "GetOzonAuth",
			Handler:    _Ozon_GetOzonAuth_Handler,
		},
		{
			MethodName: "ErrorOzonAuth",
			Handler:    _Ozon_ErrorOzonAuth_Handler,
		},
		{
			MethodName: "GetWidgetData",
			Handler:    _Ozon_GetWidgetData_Handler,
		},
		{
			MethodName: "GetProductList",
			Handler:    _Ozon_GetProductList_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Ozon_GetProduct_Handler,
		},
		{
			MethodName: "SearchShopProduct",
			Handler:    _Ozon_SearchShopProduct_Handler,
		},
		{
			MethodName: "GetUnsortedCount",
			Handler:    _Ozon_GetUnsortedCount_Handler,
		},
		{
			MethodName: "GetUnsortedList",
			Handler:    _Ozon_GetUnsortedList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozon.proto",
}
