// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: settings/v1/settings.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Settings_GetTaxes_FullMethodName         = "/settings.Settings/GetTaxes"
	Settings_SetCompanyTax_FullMethodName    = "/settings.Settings/SetCompanyTax"
	Settings_GetCompanyTaxes_FullMethodName  = "/settings.Settings/GetCompanyTaxes"
	Settings_GetCompanyTax_FullMethodName    = "/settings.Settings/GetCompanyTax"
	Settings_GetBrands_FullMethodName        = "/settings.Settings/GetBrands"
	Settings_SearchBrand_FullMethodName      = "/settings.Settings/SearchBrand"
	Settings_SetBrand_FullMethodName         = "/settings.Settings/SetBrand"
	Settings_GetCompanyBrands_FullMethodName = "/settings.Settings/GetCompanyBrands"
	Settings_GetCompanyBrand_FullMethodName  = "/settings.Settings/GetCompanyBrand"
)

// SettingsClient is the client API for Settings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsClient interface {
	GetTaxes(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*TaxesReply, error)
	SetCompanyTax(ctx context.Context, in *SetCompanyTaxRequest, opts ...grpc.CallOption) (*BoolReply, error)
	GetCompanyTaxes(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*CompanyTaxesReply, error)
	GetCompanyTax(ctx context.Context, in *GetCompanyTaxRequest, opts ...grpc.CallOption) (*CompanyTax, error)
	GetBrands(ctx context.Context, in *GetBrandsRequest, opts ...grpc.CallOption) (*BrandsReply, error)
	SearchBrand(ctx context.Context, in *SearchBrandRequest, opts ...grpc.CallOption) (*BrandsReply, error)
	SetBrand(ctx context.Context, in *SetBrandRequest, opts ...grpc.CallOption) (*BoolReply, error)
	GetCompanyBrands(ctx context.Context, in *GetCompanyBrandsRequest, opts ...grpc.CallOption) (*BrandsReply, error)
	GetCompanyBrand(ctx context.Context, in *GetCompanyBrandRequest, opts ...grpc.CallOption) (*Brand, error)
}

type settingsClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsClient(cc grpc.ClientConnInterface) SettingsClient {
	return &settingsClient{cc}
}

func (c *settingsClient) GetTaxes(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*TaxesReply, error) {
	out := new(TaxesReply)
	err := c.cc.Invoke(ctx, Settings_GetTaxes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) SetCompanyTax(ctx context.Context, in *SetCompanyTaxRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, Settings_SetCompanyTax_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) GetCompanyTaxes(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*CompanyTaxesReply, error) {
	out := new(CompanyTaxesReply)
	err := c.cc.Invoke(ctx, Settings_GetCompanyTaxes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) GetCompanyTax(ctx context.Context, in *GetCompanyTaxRequest, opts ...grpc.CallOption) (*CompanyTax, error) {
	out := new(CompanyTax)
	err := c.cc.Invoke(ctx, Settings_GetCompanyTax_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) GetBrands(ctx context.Context, in *GetBrandsRequest, opts ...grpc.CallOption) (*BrandsReply, error) {
	out := new(BrandsReply)
	err := c.cc.Invoke(ctx, Settings_GetBrands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) SearchBrand(ctx context.Context, in *SearchBrandRequest, opts ...grpc.CallOption) (*BrandsReply, error) {
	out := new(BrandsReply)
	err := c.cc.Invoke(ctx, Settings_SearchBrand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) SetBrand(ctx context.Context, in *SetBrandRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, Settings_SetBrand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) GetCompanyBrands(ctx context.Context, in *GetCompanyBrandsRequest, opts ...grpc.CallOption) (*BrandsReply, error) {
	out := new(BrandsReply)
	err := c.cc.Invoke(ctx, Settings_GetCompanyBrands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) GetCompanyBrand(ctx context.Context, in *GetCompanyBrandRequest, opts ...grpc.CallOption) (*Brand, error) {
	out := new(Brand)
	err := c.cc.Invoke(ctx, Settings_GetCompanyBrand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServer is the server API for Settings service.
// All implementations must embed UnimplementedSettingsServer
// for forward compatibility
type SettingsServer interface {
	GetTaxes(context.Context, *AuthRequest) (*TaxesReply, error)
	SetCompanyTax(context.Context, *SetCompanyTaxRequest) (*BoolReply, error)
	GetCompanyTaxes(context.Context, *AuthRequest) (*CompanyTaxesReply, error)
	GetCompanyTax(context.Context, *GetCompanyTaxRequest) (*CompanyTax, error)
	GetBrands(context.Context, *GetBrandsRequest) (*BrandsReply, error)
	SearchBrand(context.Context, *SearchBrandRequest) (*BrandsReply, error)
	SetBrand(context.Context, *SetBrandRequest) (*BoolReply, error)
	GetCompanyBrands(context.Context, *GetCompanyBrandsRequest) (*BrandsReply, error)
	GetCompanyBrand(context.Context, *GetCompanyBrandRequest) (*Brand, error)
	mustEmbedUnimplementedSettingsServer()
}

// UnimplementedSettingsServer must be embedded to have forward compatible implementations.
type UnimplementedSettingsServer struct {
}

func (UnimplementedSettingsServer) GetTaxes(context.Context, *AuthRequest) (*TaxesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaxes not implemented")
}
func (UnimplementedSettingsServer) SetCompanyTax(context.Context, *SetCompanyTaxRequest) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCompanyTax not implemented")
}
func (UnimplementedSettingsServer) GetCompanyTaxes(context.Context, *AuthRequest) (*CompanyTaxesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyTaxes not implemented")
}
func (UnimplementedSettingsServer) GetCompanyTax(context.Context, *GetCompanyTaxRequest) (*CompanyTax, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyTax not implemented")
}
func (UnimplementedSettingsServer) GetBrands(context.Context, *GetBrandsRequest) (*BrandsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrands not implemented")
}
func (UnimplementedSettingsServer) SearchBrand(context.Context, *SearchBrandRequest) (*BrandsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBrand not implemented")
}
func (UnimplementedSettingsServer) SetBrand(context.Context, *SetBrandRequest) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBrand not implemented")
}
func (UnimplementedSettingsServer) GetCompanyBrands(context.Context, *GetCompanyBrandsRequest) (*BrandsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyBrands not implemented")
}
func (UnimplementedSettingsServer) GetCompanyBrand(context.Context, *GetCompanyBrandRequest) (*Brand, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyBrand not implemented")
}
func (UnimplementedSettingsServer) mustEmbedUnimplementedSettingsServer() {}

// UnsafeSettingsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsServer will
// result in compilation errors.
type UnsafeSettingsServer interface {
	mustEmbedUnimplementedSettingsServer()
}

func RegisterSettingsServer(s grpc.ServiceRegistrar, srv SettingsServer) {
	s.RegisterService(&Settings_ServiceDesc, srv)
}

func _Settings_GetTaxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetTaxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_GetTaxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetTaxes(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_SetCompanyTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCompanyTaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).SetCompanyTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_SetCompanyTax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).SetCompanyTax(ctx, req.(*SetCompanyTaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_GetCompanyTaxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetCompanyTaxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_GetCompanyTaxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetCompanyTaxes(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_GetCompanyTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyTaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetCompanyTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_GetCompanyTax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetCompanyTax(ctx, req.(*GetCompanyTaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_GetBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_GetBrands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetBrands(ctx, req.(*GetBrandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_SearchBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).SearchBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_SearchBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).SearchBrand(ctx, req.(*SearchBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_SetBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).SetBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_SetBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).SetBrand(ctx, req.(*SetBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_GetCompanyBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyBrandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetCompanyBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_GetCompanyBrands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetCompanyBrands(ctx, req.(*GetCompanyBrandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_GetCompanyBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetCompanyBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settings_GetCompanyBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetCompanyBrand(ctx, req.(*GetCompanyBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Settings_ServiceDesc is the grpc.ServiceDesc for Settings service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Settings_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settings.Settings",
	HandlerType: (*SettingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaxes",
			Handler:    _Settings_GetTaxes_Handler,
		},
		{
			MethodName: "SetCompanyTax",
			Handler:    _Settings_SetCompanyTax_Handler,
		},
		{
			MethodName: "GetCompanyTaxes",
			Handler:    _Settings_GetCompanyTaxes_Handler,
		},
		{
			MethodName: "GetCompanyTax",
			Handler:    _Settings_GetCompanyTax_Handler,
		},
		{
			MethodName: "GetBrands",
			Handler:    _Settings_GetBrands_Handler,
		},
		{
			MethodName: "SearchBrand",
			Handler:    _Settings_SearchBrand_Handler,
		},
		{
			MethodName: "SetBrand",
			Handler:    _Settings_SetBrand_Handler,
		},
		{
			MethodName: "GetCompanyBrands",
			Handler:    _Settings_GetCompanyBrands_Handler,
		},
		{
			MethodName: "GetCompanyBrand",
			Handler:    _Settings_GetCompanyBrand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settings/v1/settings.proto",
}
